Repository proplot-dev/proplot, pull requests merged in 2021-06, with the labels that each got.

#251 Fix matplotolib 3.3.0--3.4.0 regressions
  CHANGELOG.rst
  proplot/axes/base.py
  proplot/config.py
  proplot/constructor.py
  proplot/demos.py
  proplot/figure.py
  proplot/gridspec.py
  proplot/internals/rcsetup.py
  proplot/ticker.py
Labels: bug, dependencies

#252 Return default savefig transparency to False
  CHANGELOG.rst
  docs/basics.py
  docs/projections.py
  proplot/figure.py
  proplot/internals/rcsetup.py
Labels: enhancement

#240 Permit setting 'style' to default, and add 'bbox' as 'border' alternative for inner a-b-c labels and titles
  proplot/axes/base.py
  proplot/axes/plot.py
  proplot/config.py
  proplot/internals/rcsetup.py
Labels: bug, feature
