Repository proplot-dev/proplot, pull requests merged in 2021-07, with the labels that each got.

#215 Tight layout options
  proplot/gridspec.py
  proplot/ui.py
Labels: feature

#237 Moved the metadata into setup.cfg.
  .travis.yml
  ci/environment.yml
  pyproject.toml
  setup.cfg
  setup.py
Labels: distribution

#258 Final improvements to 1D plotting wrappers
  WHATSNEW.rst
  docs/1dplots.py
  docs/_static/custom.css
  docs/axis.py
  docs/basics.py
  docs/configuration.rst
  docs/cycles.py
  docs/fonts.py
  docs/insets_panels.py
  docs/projections.py
  docs/subplots.py
  docs/why.rst
  proplot/axes/base.py
  proplot/axes/cartesian.py
  proplot/axes/geo.py
  proplot/axes/plot.py
  proplot/axes/polar.py
  proplot/colors.py
  proplot/config.py
  proplot/constructor.py
  proplot/demos.py
  proplot/figure.py
  proplot/internals/docstring.py
  proplot/internals/rcsetup.py
  proplot/internals/warnings.py
  proplot/scale.py
  proplot/ui.py
Labels: feature, refactor

#259 Plot to pplt
  docs/1dplots.py
  docs/2dplots.py
  docs/api.rst
  docs/axis.py
  docs/basics.py
  docs/colorbars_legends.py
  docs/colormaps.py
  docs/colors.py
  docs/configuration.rst
  docs/cycles.py
  docs/faq.rst
  docs/fonts.py
  docs/insets_panels.py
  docs/projections.py
  docs/subplots.py
  docs/usage.rst
  docs/why.rst
  proplot/axes/base.py
  proplot/axes/geo.py
  proplot/axes/plot.py
  proplot/axes/polar.py
  proplot/colors.py
  proplot/config.py
  proplot/figure.py
  proplot/scale.py
  proplot/tests/test_journals.py
  proplot/ticker.py
  proplot/ui.py
  proplot/utils.py
Labels: documentation
